spring:
  security:
    oauth2:
      client:
        # from 내 애플리케이션 to 네이버
        # <a href="/oauth2/authorization/naver">네이버</a> 버튼을 누르면 (사용자 -> 내 어플리케이션에 요청)
        # 1번 authorization-uri: https://nid.naver.com/oauth2.0/authorize 가 매칭돼서 진행된다
        provider:
          naver:
            # 1. 인증 요청 URL (사용자가 네이버 로그인 화면가서 로그인 및 정보제공 동의 이때 밑에 registration을 쿼리스트링으로 포함한다)
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            # 2. redirect-uri: http://localhost:8080/login/oauth2/code/naver (사용자가 redirect 돼서 내 애플리케이션으로 요청)
            # 3. Access Token 요청 URL (내 애플리케이션이 다시 네이버로 토큰 요청)
            token-uri: https://nid.naver.com/oauth2.0/token
            # 4. 사용자 정보 조회 URL (내 애플리케이션이 네이버에 트큰을 통해 정보조회)
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 응답받은 사용자 정보 중 사용자 이름이 무엇인지 담겨있는 JSON Key
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          # 네이버에 소셜로그인할때 전달해야할 정보들
          naver:
            # 네이버에 애플리케이션을 등록할 때 받은 클라이언트 ID
            client-id: c7hYcUX5EndZI9fqir94
            client-secret: gtTAe2lGvD
            # 위의 2번에 해당(사용자가 redirect 돼서 내 애플리케이션으로 요청하는 uri) 네이버한테 인증되면 여기로 다시 redirect 해달라는 정보
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            # 인증 방식을 지정
            authorization-grant-type: authorization_code
            # 인증 방법을 지정
            client-authentication-method: client_secret_post
            # 이 설정 섹션의 이름
            client-name: Naver
            # 애플리케이션이 사용자의 Naver 계정에 대해 요청하는 권한입니다
            scope:
              - nickname
              - email
              - 
              - name
              - profile_image

          kakao:
            client-id: 227bca8f8e33d954f88b474ae956ad03
            client-secret: Hn5XDZE70B32uBcsipdv1KhicWzfI2EK
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email


  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

# 커스텀 설정 (Spring 내부 설정 아님)
jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaes
